# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'
install! 'cocoapods', :integrate_targets => false

target 'libstrophe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for libstrophe
  pod "EasyAsync"
end

target 'XMPPPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XMPPPOC

end
